development:
  adapter: postgresql
  encoding: unicode
  database: organ_grinder_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: organ_grinder_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: organ_grinder_production
  pool: 5
  username: root
  password:
